# Server Configuration
[server]
port = 50051
allowed_ips = ["127.0.0.1", "192.168.1.0/24", "10.0.0.0/8"]

# Directory Sections
[[directories]]
name = "documents"
path = "./test-data/documents"
permissions = "read-only"

[[directories]]
name = "shortcodes"
path = "./test-data/shortcodes"
permissions = "read-write"

[[directories]]
name = "includes"
path = "./test-data/includes"
permissions = "read-write"
